### ISSUE TITLE
Liczba rekordów (pozycji) na stronie

### ISSUE THREAD

**Issue by Kamrat** [ziher/ziher#7]
Przydałoby się aby dało się ustawić ilość wyświetlanych pozycji na stronie obecne 10 czasami to jest 20% z możliwości wyświetlenia na ekranie.

**Comment by perk** [comment]
Z emaila:
> Możliwość podglądu całej książki poprzez scrollowanie w dół – przy kilkudziesięciu operacjach w trakcie roku kolejne pozycje przenoszone są na kolejne strony KF. Łatwiej by się pracowało, gdyby były widoczne na jednej stronie, po prostu zjeżdżając w dół strony.
